---
abstract: 'historic forex rates from openexchangerates.org'
author:
  - 'Bhavin Patel <mail4bhavin@gmail.com>'
build_requires:
  English: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132510'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Forex
no_index:
  directory:
    - t
    - inc
requires:
  DateTime: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Test::More: 0
version: 1.3
